name: Gatsby Publish

on:
  push:
    branches:
      - source
  repository_dispatch:
    types: [gatsby-publish]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
